apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-worker
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: worker-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 30