apiVersion: v1
entries:
  multi-container-worker:
  - apiVersion: v2
    created: "2022-06-12T14:52:09.339759775+01:00"
    description: A Helm chart for worker micro-service
    digest: b4dcb17dac01833de4907dd8ce64571efeaf1bdb65541bae776e38b93aa8a58b
    icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
    name: multi-container-worker
    urls:
    - multi-container-worker-0.2.0.tgz
    version: 0.2.0
generated: "2022-06-12T14:52:09.339035793+01:00"
