apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    component: {{ .Values.deployment.component }}
  
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.deployment.component }}
  template:
    metadata:
      name: {{ .Values.deployment.templateName }}
      labels:
        component: {{ .Values.deployment.component }}
    spec:
      containers:
        - name: {{ .Values.deployment.imageName }}
          image: {{ .Values.deployment.image }}
          env:
           {{- range .Values.env }}
           - name: {{ .name }}
             value: {{ .value | quote }}
           {{- end }} 
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m