apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    component: worker
  
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      name: worker
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: ahmedaminesoltani/multi-worker:latest
          env:
            - name: REDIS_HOST 
              value: redis-service
            - name: REDIS_PORT
              value: '6379'