apiVersion: v1
kind: Pod
metadata:
  name: myapp-2
  labels: 
    app: myapp
spec:
  containers:
    - name: client
      image: nginx
      ports:
        - containerPort: 80
  #nodeName: "gke-cluster-1-default-pool-75c1e525-sxbn"