apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  namespace: lab
  labels:
    app: myapp

spec:
  template:
    metadata:
      name: myapp
      labels: 
        component: web
        app: myapp
    spec:
      containers:
        - name: client
          image: nginx
          ports:
            - containerPort: 80
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"
      #nodeName: "gke-cluster-1-default-pool-75c1e525-0kms"
  replicas: 1
  selector: 
    matchLabels:
      app: myapp