apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp

spec:
  template:
    metadata:
      name: myapp
      labels: 
        component: web
        app: myapp
    spec:
      containers:
        - name: client
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3
  selector: 
    matchLabels:
      app: myapp