apiVersion: v1
entries:
  multi-container-redis:
  - apiVersion: v2
    created: "2021-10-15T15:09:50.824460693+02:00"
    description: A Helm chart for redis micro-service
    digest: def6979f9dbbc3f68ed784011c54a563caa5e59535c3816e8375401c7ef18893
    icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
    name: multi-container-redis
    urls:
    - multi-container-redis-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-15T15:09:50.824133883+02:00"
